language: java
deploy:
  provider: heroku
  api_key:
    secure: eqv0+g3KTS65dE7dj3P8ZpIXgnPDtBoVOHSwp6/tDFJGH1xIti9D4hfHM8cqU2v/aXbRjGPyFBbKf7jg91JQJPLOKyb0br8m9JM4a3qNcKOFCwzg6oH+7VY/bgip3YT2feMjCF9iNVSOcd0Vmq5QC5+QZFVBRa3+SOAGF6j0YcGjnQI4u99IzQFI7Z14CzQwgu9auZ9A5gt2Hg+0Jef3F4qADhk4lc4neiU3ARzVPdkrp/BQItK6Qp3V4gcxOMyy3Ze/Uj1mKBwHMgvveWDB13jYgGgqN6uE9xOe1qzjmCrGmsE5u/yq3qidLUmXEw+i8x0Bqv2nZNqX1mmdNSUKgDugVR5O5JuiEePqxvn6NTxFIq967AE741aIeVAqopoyo/TFxnEcpbTRJ41wb3tHRp7x8AzOOR4zw2lNrNGMptQHCtLwmJlT43OHeH0o0yP6ovQe6NBJuoXOaPMftxa7q+2Lj/0Y3bmVgsvZst9Tsu0aUYG2c1uozE2VGXEqak+E6MkzdKRE6GdHZVchRFnropcdnfqSe9nxVeaNzGFmeggZYSyBKMDg1rrcZQewVbIdKK9uNB3kpKvNeJAr6oIJrPJcUAfyZUl07CZR/LnpP2cr0dwrjzdBJVc+94X573w8XQq7G1L2UmJ72vvci61VUrUPRNHfjSgTdzwupQTikiw=
  app: secret-wave-52844


